title: even janken
email: info@evenjanken.nl
description: >- # this means to ignore newlines until "baseurl:"
  Soms moet er even gejankt worden, dat kan hier.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.evenjanken.nl" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Thijs Erends
  email: sitemaster@evenjanken.nl

# Build settings
remote_theme: jekyll/minima
minima:
  skin: auto
  date_format: "%a, %-d %b %Y"
  social_links:
  - { platform: github,         user_url: "https://github.com/matglas2/matglas2.github.io" }
#   - { platform: devto,          user_url: "https://dev.to/jekyll" }
#   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
#   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
#   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
#   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
#   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
#   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
#   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
#   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
#   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
#   - { platform: telegram,       user_url: "https://t.me/jekyll" }
#   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title
      author: Thijs Erends
      layout: post
      pretitle: even janken om
